// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import (
	domain "go-todo/domain"

	mock "github.com/stretchr/testify/mock"
)

// TodoService is an autogenerated mock type for the TodoService type
type TodoService struct {
	mock.Mock
}

// Create provides a mock function with given fields: data
func (_m *TodoService) Create(data domain.Todo) (domain.Todo, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Todo) (domain.Todo, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(domain.Todo) domain.Todo); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}

	if rf, ok := ret.Get(1).(func(domain.Todo) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TodoService) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TodoService) GetAll() ([]domain.Todo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Todo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *TodoService) GetById(id int) (domain.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Todo); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, data
func (_m *TodoService) Update(id int, data domain.Todo) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.Todo) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoService creates a new instance of TodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoService {
	mock := &TodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
